# Generated by Django 4.0.6 on 2022-07-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_card_remove_transaction_symbol_currency_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Third_Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=10)),
                ('isActive', models.BooleanField(max_length=3)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
            ],
        ),
    ]
