# Generated by Django 4.0.6 on 2022-07-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField()),
                ('bill_number', models.PositiveIntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
