# Generated by Django 4.0.6 on 2022-07-30 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=2)),
                ('age', models.PositiveSmallIntegerField()),
                ('user_id', models.CharField(max_length=7)),
                ('nationality', models.CharField(max_length=12, null=True)),
                ('occupation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField()),
                ('pin', models.SmallIntegerField()),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.currency')),
            ],
        ),
    ]
