# Generated by Django 4.0.6 on 2022-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.TextField()),
                ('account_name', models.CharField(max_length=10)),
                ('deposit', models.PositiveIntegerField()),
                ('withdrawals', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=8)),
                ('transaction_amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(max_length=4)),
            ],
        ),
    ]
