# Generated by Django 4.0.6 on 2022-07-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_remove_third_party_name_notification_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
                ('payment_due_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.third_party')),
            ],
        ),
    ]
